### ISSUE TITLE
Issues from DiscordGo

### ISSUE THREAD

**Issue by switchupcb** [switchupcb/disgo#23]
Disgo solves the following issues from https://github.com/bwmarrin/discordgo/issues.

**Comment by switchupcb** [comment]
https://github.com/bwmarrin/discordgo/issues/513 (by @erikmcclure) outlines a potential deadlock scenario that involves the calling of multiple `Connect()` and `Disconnect()` equivalent-calls while a Opcode 11 Heartbeat ACK is received. 

Disgo avoids this issue through multiple mechanisms:
1. Only one connect action can occur at at any given time through the usage the Session's only mutex.
2. A heartbeat will only be sent to a channel (via `s.heartbeat.send`) when another goroutine is listening to that channel (`s.heartbeat.send`) due to the `manager` mechanism _(which prevents the heartbeat goroutine from closing BEFORE goroutines that can generate heartbeats)_.
3. This is not highlighted on the golangci-linter, while this user's alert of this issue occurs from that same linter.
4. We use a test to connect, disconnect, and reconnect to the API with `-race`.

**Comment by switchupcb** [comment]
https://github.com/bwmarrin/discordgo/issues/544 outlines the possibility for Discord to send an Opcode 9 Invalid Session (which warrants a re-identify) upon a reconnection attempt. This is handled by Disgo in the [`session.go` `initial` function](https://github.com/switchupcb/disgo/blob/v10/wrapper/session.go#L216).

**Comment by switchupcb** [comment]
The following (open) issues have occurred due to an incorrect type definition or non-existent type definition in relation to JSON tags:
- https://github.com/bwmarrin/discordgo/issues/571 (by @azplay)
- https://github.com/bwmarrin/discordgo/issues/714 (by @ravener)
- https://github.com/bwmarrin/discordgo/issues/734 (by @JurrijnP)
- https://github.com/bwmarrin/discordgo/issues/808 (by @aequasi)
- https://github.com/bwmarrin/discordgo/issues/994 (by @Bendodroid)

Disgo avoids these issues through the usage of [Dasgo](https://github.com/switchupcb/dasgo). In short, @bwmarrin and @FedorLap2006 may benefit from using Dasgo to stay up-to-date while reducing maintenance load.

**Comment by switchupcb** [comment]
The following **open** issues have occurred due to an incorrect type definition or non-existent type definition:
- https://github.com/bwmarrin/discordgo/issues/946 (by @Minecodes)
- https://github.com/bwmarrin/discordgo/issues/951 (by @FedorLap2006)

There are 8 open issues and 37 closed issues with the query [`missing`](https://github.com/bwmarrin/discordgo/issues?q=is%3Aissue+missing+is%3Aclosed).

Disgo avoids these issues through the usage of [Dasgo](https://github.com/switchupcb/dasgo). In short, @bwmarrin and @FedorLap2006 may benefit from using Dasgo to stay up-to-date while reducing maintenance load.

**Comment by switchupcb** [comment]
https://github.com/bwmarrin/discordgo/issues/649 (by @UlisseMini) outlines a concern with the `New` function in discordgo. While this isn't inherently an issue, it abstracts how the client is being initialized. In actuality, `New` initializes a session which represents a "bot" client. This abstraction can be confusing since a WebSocket Session isn't actually required to send requests, and there is no guarantee that the user needs an initialized "WebSocket Session".

Disgo avoids this confusion by being explicit in its idiomatic initialization, at the cost of a few extra lines.

**Comment by switchupcb** [comment]
https://github.com/bwmarrin/discordgo/issues/712 (by @riking) outlines an issue with the ratelimiting functionality of DiscordGo. Specifically, a per-resource per-route rate limit issue: This is being addressed by Disgo in https://github.com/switchupcb/disgo/issues/22, and will be possible to implement without a refactor.

**Comment by switchupcb** [comment]
https://github.com/bwmarrin/discordgo/issues/966 (by @sntran) outlines an issue with a lack of support for the OAuth2 flow _Client Credentials Grant_. Disgo implements and provides steps for all OAuth2 flows in [`oauth2.go`](https://github.com/switchupcb/disgo/blob/v10/wrapper/oauth2.go).

**Comment by FedorLap2006** [comment]
We're currently working on getting the types up to date, in particular partial and null fields.

**Comment by FedorLap2006** [comment]
Thank you for outlining some of the older issues though

**Comment by switchupcb** [comment]
> We're currently working on getting the types up to date, in particular partial and null fields.
> — @FedorLap2006 

Great! If you haven't already, you can consider using **Dasgo**. We realized that every Go Discord API Wrapper was having trouble with missing fields, or incorrectly defined fields in relation to JSON. In order to solve this issue, we created a Go API Types Library for the Discord API called [Dasgo](https://github.com/switchupcb/dasgo). This library is built with a specification and is not implementation specific to Disgo; meaning that other Go API Wrappers can use it for their types. If Dasgo is used by many API Wrappers, we can unite the entire Discord Go community while still allowing multiple API Wrappers to exist.

Dasgo has more benefits beyond type definitions. As an example, [`discordgo's wsapi.go L112`](https://github.com/bwmarrin/discordgo/blob/master/wsapi.go#L112) features a magic number "10". In actuality, this number refers to an Opcode 10 Hello which is represented in Dasgo by [`FlagGatewayOpcodeHello`](https://github.com/switchupcb/dasgo/blob/v10/dasgo/codes.go#L16). This occurs again at [`wsapi.go` L127`](https://github.com/bwmarrin/discordgo/blob/master/wsapi.go#L127) (Dispatch), 140 (Resume), and even for strings such as L179. If Dasgo was used here, the reader of the code would be able to clearly identify the reason for the literal number or string that is used.

Dasgo doesn't have to be used as a dependency, and can be derived from code generation (as shown by Disgo). If you need assistance with that, feel free to let me know! With more people focusing on Dasgo to fix changes like these, maintainers will have less work to do when Discord rolls out an inevitable change.

**Comment by switchupcb** [comment]
The following pull requests are also related to the issues addressed in https://github.com/switchupcb/disgo/issues/23#issuecomment-1196664510.
- https://github.com/bwmarrin/discordgo/pull/1002 (@corbmr)
- https://github.com/bwmarrin/discordgo/pull/1192 (@JABirchall)
- https://github.com/bwmarrin/discordgo/pull/1199 (@iokill)
- https://github.com/bwmarrin/discordgo/pull/1210 (@drlau)
- https://github.com/bwmarrin/discordgo/pull/1211 (@plally)

**Comment by switchupcb** [comment]
The following issues are solved by using Dasgo.

- https://github.com/bwmarrin/discordgo/issues/1200 (@fafafwawe)

**Comment by switchupcb** [comment]
The following issues are avoided by using Automatic Intent Calculation.

- https://github.com/bwmarrin/discordgo/issues/1270
- https://github.com/bwmarrin/discordgo/issues/1264

**Comment by switchupcb** [comment]
@FedorLap2006, join the Disgo side. We have cookies... Strictly necessary of course.

**Comment by switchupcb** [comment]
@Strum355 So [predictable](https://prnt.sc/QFsWSP2cQ2Ih).

![a png](https://user-images.githubusercontent.com/81384235/205738430-5ca887a3-1106-46ed-937d-cc7a5ea7e041.jpg)

**Comment by Strum355** [comment]
thanks for the content, looks great in a github platform abuse report :slightly_smiling_face:
