### ISSUE TITLE
question: How to store the state of a Guild that went unavailable?

### ISSUE THREAD

**Issue by erkinalp** [switchupcb/disgo#35]
This case is planned to be utilised in fosscord to implement a simple IRC/XMPP-style federation of fosscord servers.

**Comment by switchupcb** [comment]
_Thanks for using Disgo in its Beta release. Your help is appreciated in bringing us closer to a production-ready release._

The documentation for a [Guild Create](https://discord.com/developers/docs/topics/gateway-events#guild-create) event outlines what happens when a guild becomes unavailable (due to an outage or user removal). To be specific the [Guild Delete](https://discord.com/developers/docs/topics/gateway-events#guild-delete) is sent when a guild becomes unavailable. At the current time, Disgo supports every event (and respective event handling). **Can you please explain how you want this to be handled beyond the current implementation?** Alternatively, are you looking for help on implementing the handler for this case?

**Comment by erkinalp** [comment]
In case of the planned fosscord federation, the guilds can go unavailable without completely disappearing (metadata known, retrieval partially possible, but no modification can be accepted), hence the need to gracefully handle the case of unavailable guilds in Guild Update events.

**Comment by switchupcb** [comment]
The [Guild Update](https://discord.com/developers/docs/topics/gateway-events#guild-update) event is supported by Disgo. I would note that Discord does not send Guild Update events while a Guild is `unavailable`. Once the guild becomes avaliable again, your bot would receive a Guild Create Event.

**Comment by switchupcb** [comment]
As far as gracefully handling this case goes, I believe that Disgo already supports this behavior. If you wish to manually store the state of the guild upon it becoming unavailable, you can do that with the following **psuedocode**. This code will be applicable until the Cache Manager is implemented; if manual caching isn't already preferred.

```go
package main

import (
	"fmt"
	"log"
	"sync"

	disgo "github.com/switchupcb/disgo/wrapper"
)

func main() {
	// cache represents a map of Snowflake IDs to Guilds (map[string]disgo.Guild).
	cache := new(sync.Map)

	// Create a client.
	bot := &disgo.Client{
		Authentication: disgo.BotToken("TOKEN"),
		Config:         disgo.DefaultConfig(),
		Handlers:       new(disgo.Handlers),
		Sessions:       []Sessions{disgo.NewSession()},
	}

	// Create the handler for the Guild Create event.
	bot.Handle(disgo.FlagGatewayEventNameGuildCreate, func(g disgo.GuildCreate) {
		cached, ok := cache.Load(g.Guild.ID)

		// when the guild isn't in the cache, store it.
		if !ok {
			cache.Store(g.Guild.ID, g.Guild)

			return
		}

		// when the guild already exists in the cache, update it.
		cachedGuild := cached.(disgo.Guild)

		// This example simply replaces the stored guild, such that the cache is read-only.
		//
		// In cases where you want to modify guilds (values) within the cache,
		// create an object (struct) that stores both a Guild and Mutex (Lock).
		cache.Store(g.Guild.ID, g.Guild)
	})

	// Create the handler for the Guild Update Event.
	bot.Handle(disgo.FlagGatewayEventNameGuildUpdate, func(g disgo.GuildUpdate) {
		cached, ok := cache.Load(g.Guild.ID)

		// when the guild isn't in the cache (for whatever reason), store it.
		if !ok {
			cache.Store(g.Guild.ID, g.Guild)

			return
		}

		// when the guild already exists in the cache, update it.
		cachedGuild := cached.(disgo.Guild)

		// This example simply replaces the stored guild, such that the cache is read-only.
		//
		// In cases where you want to modify guilds (values) within the cache,
		// create an object (struct) that stores both a Guild and Mutex (Lock).
		cache.Store(g.Guild.ID, g.Guild)
	})

	// Create the handler for the Guild Delete event.
	bot.Handle(disgo.FlagGatewayEventNameGuildDelete, func(g disgo.GuildDelete) {
		// Handle guilds that experience unavailability here.
		//
		// Do note that unavailable guilds only have the ID and unavailable fields present.
		if g.Unavailable {
			log.Printf("Guild %s is experiencing an outage.", g.Guild.ID)
		} else {
			// when a Guild has been deleted or the bot has been removed from or left the guild.
			log.Printf("Guild %s is unaccessible to the bot.")
		}

		// retrieve the last known state of the guild.
		if cached, ok := cache.Load(g.Guild.ID); ok {
			cachedGuild := cached.(disgo.Guild)

			// use cachedGuild.FIELD to access a read-only state of the unavailable guild.
			log.Printf("The previous known state of Guild %s: %v", g.Guild.ID, cachedGuild)
		}
	})

	// Connect the bot session to the Discord Gateway (WebSocket Connection).
	if err := bot.Sessions[0].Connect(bot); err != nil {
		log.Printf("can't open websocket session to Discord: %v", err)
	}

	// During runtime, retrieve the state of any Guild using the cache.
	cached, ok := cache.Load("SNOWFLAKE")
	cachedGuild := cached.(disgo.Guild)
	if cachedGuild != nil {
		fmt.Println(cachedGuild.name)
	}
}
```

**Comment by switchupcb** [comment]
If there are any other questions, feel free to let me know.

**Comment by erkinalp** [comment]
> The [Guild Update](https://discord.com/developers/docs/topics/gateway-events#guild-update) event is supported by Disgo. I would note that Discord does not send Guild Update events while a Guild is unavailable.

Yeah, I know that. [Fosscord](https://github.com/fosscord/fosscord-server) is a third party server reimplementation. Due to architectural differences, the case I described can actually happen on fosscord.
