### ISSUE TITLE
request: message components format error

### ISSUE THREAD

**Issue by skifli** [switchupcb/disgo#67]
I'm trying to send a message with components. However as there are currently no documentation for sending messages with components, I have had to guess how to format the payload, and I'm not sure what is wrong with it. It errors out with `Failed to respond to an interaction: REQUEST ERROR: client - error: status code 400: The request was improperly formatted, or the server couldn't understand it`. If you could kindly tell me what is wrong, then thanks.

```go
response := &disgo.CreateInteractionResponse{
	InteractionID:    interaction.ID,
	InteractionToken: interaction.Token,
	InteractionResponse: &disgo.InteractionResponse{
		Type: disgo.FlagInteractionCallbackTypeCHANNEL_MESSAGE_WITH_SOURCE,
		Data: &disgo.Messages{
			Embeds: []*disgo.Embed{
				{
					Title:       disgo.Pointer("Rock, Paper, Scissors"),
					Description: disgo.Pointer(fmt.Sprintf("Choose your weapon <@%s>!", interaction.Member.User.ID)),
					Color:       disgo.Pointer(6591981),
					Footer:      &disgo.EmbedFooter{Text: "Run /about for more information about the bot."},
				},
			},
			Components: []disgo.Component{
				disgo.ActionsRow{
					Components: []disgo.Component{
						&disgo.Button{
							Label:    disgo.Pointer("Rock"),
							CustomID: disgo.Pointer("rock"),
							Emoji: &disgo.Emoji{
								Name: disgo.Pointer("U0001F9FA"),
							},
						},
						&disgo.Button{
							Label:    disgo.Pointer("Paper"),
							CustomID: disgo.Pointer("paper"),
							Emoji: &disgo.Emoji{
								Name: disgo.Pointer("U0001F4DC"),
							},
						},
						&disgo.Button{
							Label:    disgo.Pointer("Scissors"),
							CustomID: disgo.Pointer("scissors"),
							Emoji: &disgo.Emoji{
								Name: disgo.Pointer("U00002702"),
							},
						},
					},
				},
			},
		},
	},
}
```

**Comment by skifli** [comment]
The code can be found [here](https://github.com/skifli/creft/blob/main/commands/games/rps.go#L16).

**Comment by switchupcb** [comment]
Disgo is a 1:1 API Wrapper which means all formatting rules are provided by Discord's Documentation (on Message Components): https://discord.com/developers/docs/interactions/message-components

Your `ActionsRow` component and its subsequent child components are missing the required `Type` field(s). 

You must add the required fields to these objects.
- Action Row has a `type = 1`: https://discord.com/developers/docs/interactions/message-components#action-rows
- Buttons have a `type = 2`: https://discord.com/developers/docs/interactions/message-components#buttons
- Buttons `style` field is also required: https://discord.com/developers/docs/interactions/message-components#button-object-button-styles

In Disgo, `types` and `styles` are [flags](https://github.com/switchupcb/disgo#flags).

**Comment by skifli** [comment]
> Disgo is a 1:1 API Wrapper which means all formatting rules are provided by Discord's Documentation (on Message Components): https://discord.com/developers/docs/interactions/message-components
> 
> Your `ActionsRow` component and its subsequent child components are missing the required `Type` field(s).
> 
> You must add the required fields to these objects.
> 
>     * Action Row has a `type = 1`: https://discord.com/developers/docs/interactions/message-components#action-rows
> 
>     * Buttons have a `type = 2`: https://discord.com/developers/docs/interactions/message-components#buttons
> 
>     * Buttons `style` field is also required: https://discord.com/developers/docs/interactions/message-components#button-object-button-styles

Yes, I know this as I have worked directly with the Discord API before. However, the field `Type` is not part of any of the structures.

![image](https://github.com/switchupcb/disgo/assets/121291719/e1cac2ca-6af5-48de-835d-6b1f8a2e4f41)
![image](https://github.com/switchupcb/disgo/assets/121291719/f76c79a3-4e75-4423-a2f8-db1359780155)

**Comment by skifli** [comment]
Furthermore, the structs all have a ComponentType field, that is pre-written. Maybe the function isn't being called correctly?
![image](https://github.com/switchupcb/disgo/assets/121291719/51f99abc-df20-4785-9c82-0f8964c9249d)

**Comment by switchupcb** [comment]
Actions Row is missing a documented structure in the Discord Documentation. This led to a misconfiguration of the `ActionsRow`, `Button`, and `TextInput` structs (missing `type` field). Therefore, the solution is to add the missing fields to [dasgo](https://github.com/switchupcb/dasgo).

**Comment by switchupcb** [comment]
@skifli Sending message components has been fixed in the latest commit. Use `go get github.com/switchupcb/disgo@update` to import it.

_An [example](https://github.com/switchupcb/disgo/tree/v10/_examples/message/components) has also been added._

**Comment by skifli** [comment]
> @skifli Sending message components has been fixed in the latest commit. Use `go get github.com/switchupcb/disgo@update` to import it.
> 
> _An [example](https://github.com/switchupcb/disgo/tree/v10/_examples/message/components) has also been added._

Thank you.
