### ISSUE TITLE
question: How to send an Ephemeral Message in an Interaction Response?

### ISSUE THREAD

**Issue by skifli** [switchupcb/disgo#68]
How do you send Ephemeral messages? I cannot find any docs for them.

**Comment by switchupcb** [comment]
When the definition of an ephemeral message fits the description provided by [Discord Support (Epheremeral Messages)](https://support.discord.com/hc/en-us/articles/1500000580222-Ephemeral-Messages-FAQ), these messages are created when the bot responds to a user using slash commands.

This behavior occurs when the bot [creates a followup message](https://discord.com/developers/docs/interactions/receiving-and-responding#create-followup-message) with a `flag = 64` or in certain defaults.

> flags can be set to 64 to mark the message as ephemeral, except when it is the first followup message to a deferred Interactions Response. In that case, the flags field will be ignored, and the ephemerality of the message will be determined by the flags value in your original ACK.
> 
> — Discord Documentation

You can read the [disgo command: followup example](https://github.com/switchupcb/disgo/tree/v10/_examples/command/followup) for a demonstration that sends followup messages to an interaction using `disgo`.

_Please let me know if you need more information._

**Comment by skifli** [comment]
Thank you, it worked.
